#Spring Boot Project 에 추가된 Library 관리.

#db source url
#spring.datasource.url=jdbc:mysql://localhost:3306/moiming_database?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul

#db response name
#spring.datasource.username=root

#db response pw
#spring.datasource.password=Sdc00135!@

#dbsql 확인하는 옵션 문 -> run 에서 실행한 SQL문도 확인할 수 있도록 하는 것.
#spring.jpa.show-sql=true

#JSON 으로 보낼 때 스네이크 케이스로 이름 바꾸어주는 설정.
#spring.jackson.property-naming-strategy=SNAKE_CASE

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/moiming_database?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: Sdc00135!@

  jpa:
    show-sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE


jwt:
  header: Authorization
  secret: bW9pbWluZy1yZWxlYXNlLXZlcnNpb24tMjEwNjA2LWp3dC1zZWNyZXQta2V5LWNyZWF0ZWQtdG9kdGpkV0stUmtkRG5UanIK
  token-validity-in-seconds: 86400